# .github/workflows/deploy-s3.yml
name: Deploy Vite App to S3

on:
  push:
    branches:
      - master

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_S3_BUCKET_NAME: ${{ secrets.AWS_S3_BUCKET_NAME }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  VITE_API_SERVER_HOST: ${{ secrets.VITE_API_SERVER_HOST }}


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Create .env for Vite
        run: |
          cat > .env <<EOF
          VITE_API_SERVER_HOST=${{ secrets.VITE_API_SERVER_HOST }}
          EOF

      - name: Install dependencies
        run: npm ci

      - name: Build Vite app
        run: npm run build

      - name: Verify dist directory
        run: |
          ls -R .
          if [ ! -d dist ]; then
            echo "dist/ 폴더가 없습니다!"
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Sync dist to S3 (no ACL)
        run: |
          echo "→ s3://${{ env.AWS_S3_BUCKET_NAME }}/ 에 dist/ 동기화 시작"
          aws s3 sync dist/ s3://${{ env.AWS_S3_BUCKET_NAME }}/ \
            --delete

      - name: Invalidate CloudFront cache
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION:           ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }}
          PATHS:                  "/*"
          AWS_REGION:             ${{ env.AWS_REGION }}
          AWS_ACCESS_KEY_ID:      ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
